[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "31ugT3J6nYenT2LSaDtFRF5ro3hQffsKJY21CgyXeCzS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dark/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
